spring:
  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  #      ddl-auto: validate

#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        trace: false
#        web-allow-others: false

  datasource:
    generate-unique-name: false
#    url: jdbc:h2:mem:graphql-demo;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
    url: jdbc:mysql://localhost:3306/springbook?serverTimezone=Asia/Seoul
    username: spring
    password: Springbook@123
    driver-class-name: com.mysql.cj.jdbc.Driver

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true
  servlet:
    mapping: /graphql
    enabled: true
    websocket:
      enabled: false